name: build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        set CC=cl
        set CXX=cl
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    - name: make
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake --build build
    - name: dist
      shell: cmd
      run: |
        mkdir dist
        copy build\nlasvc2.dll dist
        copy install.reg dist
        copy Update-Offset.ps1 dist
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ncsi-override-amd64
        # Directory containing files to upload
        path: dist
    - name: package for release
      shell: powershell
      run: |
        cd dist
        Compress-Archive . ..\ncsi-override-amd64.zip
    - name: prerelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Latest Development Build"
        files: |
          ncsi-override-amd64.zip